### ISSUE TITLE
Generate API token during bootup and store as a K8s Secret

### ISSUE THREAD

**Issue by code4dc** [cratekube/cratekube#43]
### Problem to solve
CrateKube Platform services need to communicate with each other securely via a secret bearer token.

### Proposal
The bearer token should be generated as UUID in the bootstrap code and stored as a Kubernetes secret. This secret can then be read by each CrateKube service's deployment.yml file into the ADMIN_APIKEY environment variable. 

### Intended users
N/A 

### Further details
This is how the secret will be read by other CrateKube services:
```
 env:
            - name: ADMIN_APIKEY
              valueFrom:
                secretKeyRef:
                  name: cloud-mgmt-secret
                  key: ssh-public-key
```

### Permissions and Security
N/A

### Documentation
Update Bootstrap documentation to reflect the generation and storage of the ADMIN_APIKEY

### How can we measure success?
N/A

### When is this feature complete?
We can stand up the cloud-mgmt-service successfully with the ADMIN_APIKEY correctly loaded.  

### Links / references
Where to insert key generation and secret storage: 
https://github.com/cratekube/cratekube/blob/d6adcaae1acab10a981e77afd5ccd67307377de5/src/main/groovy/io/cratekube/cli/service/WorkerNodeService.groovy#L89
